version: "2"
services:

    client:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api

    api:
        build: ./api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./api/data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
    
    